### ISSUE TITLE
create cli to create demo lom records

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-records-lom#24]
- [ ] As in other datamodel modules there has to be a cli to create demo records. (Like https://github.com/tu-graz-library/invenio-records-marc21/blob/c1a0830cb7da756e2284cb7685f86a498428eff5/invenio_records_marc21/cli.py#L144, https://github.com/inveniosoftware/invenio-rdm-records/blob/66e4f03551a7c3a03cb2705bd0c6f417e5ed407d/invenio_rdm_records/cli.py#L31)
- [ ] Create the directory "fixtures" and place all what is necessary to create fake records there. (Like: https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/fixtures)
- [ ] Write tests to verify that all is working as expected

**Comment by martinobersteiner** [comment]
Metadata creation, CLI, tests and printing created metadata to console were added in #25.
CLI-command was changed to publish to the database instead of printing to console, in #27.
CLI-command was changed to publish linked records of different `resource_type`s (`course`, `unit`, `file`), in #28 .
